language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    # secure: agnYT/4GhGCxFXcZznjIh6r4IeLHWOB/eNLudRX/veuHmZst8ETP/00xPsHTtYwS3D23gLtFvrFrWIDpGqiNVKL8wA4W1Aa+5WMtguThruCZOPuzhz6s2VdKVlZOFkx/RRvRIPuSLjBMRwiNTB5IfQ8BKJwRpFbX5q4nmyddRBcqXvAnnEXW28m7LlZjNX2pUA75/R/1pRcVRooOSUYDk/NynFjJ/xppsrYN7wTtIquj/bIGIadD9UZM2XQeCBd0jl28a7Lh4MZO1k9RnbZHNsuQl8Ar7sirVSxSrkiU06PW85e/EH0IybE2BNiTKlLXnG41jrWbtMdGmoPaGyJ5o66MPQ/RiOm8HB080a3lxD9TyYrDS8fmUuC1OtI/E1bQmvBTRIeXWqOTCsAKi9Jalx7wI9I0VdcZl9Z3JHSr42SQkPSp7QRT90SDe0bQdIYCtCuxOtJHzFCSgpKoFq5fdPqxj82AEcQE+E9UrkIT4lr1wTRgzs9119eZU8XMEvKj4l99ltxTo7Lrg/sx97THNe6b4P6t1bCvT/dudIAk+2KoU5IWLJQWssAhHmpMnx5FmkYmkv/hhVwnRNi5vU61tXr2mU6sW4S5P7DQq3JaziWnJFBbsQEPfa0RNHz2gA6+1Jbj1gZlTAydppL4VUKxc5DOPkqR30aWkggeOXyKET8=
    scure: b92171a1-a4cf-4fde-9acc-1feffeddc4fb
  app: young-reef-15784
  on:
    repo: benparman/waterSpotter
    branches:
    only: master
